In [74]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [66]:
# Categories array
categories = [ # each category represent the ML-answer from as many separate models
                'is_blurry',
                'has_identified_objects',
                'contains_common_identified_objects',
                'contains_text',
                'has_exif_data',
                'is_created_at_time_near_neighbor_file',
                'is_created_geographically_close_to_neighbor_file',
                'seems_like_screenshot',
                'seems_very_dark',
                'seems_very_light',
            ]

In [67]:
# Create representation of image files
random_array = np.random.choice([0,1],size=(10000, 10))
print(random_array)

[[0 1 1 ... 1 0 0]
 [1 0 1 ... 0 0 0]
 [1 1 0 ... 1 0 0]
 ...
 [1 1 0 ... 0 0 1]
 [1 0 1 ... 1 0 0]
 [1 1 0 ... 1 1 1]]


In [68]:
# create an answer array (y)
y = np.ndarray((10000,1))
# print(y)

# y(keep=0) == file.delete()

for index, answer in enumerate(y):
    if random_array[index][0] < 0.2 and random_array[index][2] == 1 and random_array[index][3] < 0.3:
        y[index] = 1
    else:
        y[index] = 0

print(np.count_nonzero(y, axis=0))

[1172]


In [71]:
# build the dataframes
X = pd.DataFrame(random_array, columns=categories)
# print(X) -- DONE!
y = pd.DataFrame(y, columns=['Keep_or_Throw'])
# print(y) -- DONE!

      Keep_or_Throw
0               0.0
1               0.0
2               0.0
3               0.0
4               0.0
...             ...
9995            0.0
9996            1.0
9997            0.0
9998            0.0
9999            0.0

[10000 rows x 1 columns]


In [72]:
# split X and y data training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


AttributeError: 'DataFrame' object has no attribute 'label'

In [52]:
# (m * n)(n * p)
print(np.shape(X))
print(np.shape(y))

print(np.concatenate((y.T, X.T)))

(10000, 10)
(10000,)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [48]:
endimensionell = np.ndarray((10,1))

print(endimensionell)

[[2.90200676e-315]
 [0.00000000e+000]
 [6.72707967e-310]
 [6.72707967e-310]
 [6.72707967e-310]
 [6.72707967e-310]
 [6.72707967e-310]
 [6.72707967e-310]
 [6.72707967e-310]
 [6.72707967e-310]]


In [60]:
grunddata = np.array([[1,1],[10,0],[4,0]])
print(np.shape(grunddata))
print(grunddata)
print(grunddata[:,1:1])
grunddata2 = np.array([[1],[1][0]])

concattat = np.concatenate((grunddata, grunddata2))

(3, 2)
[[ 1  1]
 [10  0]
 [ 4  0]]
[]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.