In [2]:
import numpy as np

[[0 0 1 ... 0 0 0]
 [0 1 0 ... 1 0 0]
 [1 0 0 ... 1 1 1]
 ...
 [1 1 1 ... 1 0 0]
 [0 1 1 ... 1 1 0]
 [1 1 0 ... 1 1 1]]


In [2]:
import pandas as pd
import numpy as np
import random

source_data_df = pd.DataFrame(np.random.randint(0,high=2,size=(10000, 10)))
source_data_pd = np.random.choice([0,1], size=(10000,10))
print(source_data_df)
print(source_data_pd)

      0  1  2  3  4  5  6  7  8  9
0     1  1  0  0  1  1  0  0  0  0
1     0  0  1  1  1  1  1  1  0  0
2     0  1  0  0  0  1  1  0  0  0
3     0  0  0  0  1  0  1  0  0  1
4     0  0  1  1  1  0  0  1  0  1
...  .. .. .. .. .. .. .. .. .. ..
9995  0  1  1  0  0  0  0  1  1  0
9996  1  0  0  1  0  0  0  1  0  1
9997  1  0  1  1  1  0  1  1  0  1
9998  1  0  1  0  0  0  1  0  1  1
9999  1  1  0  1  1  0  1  0  0  0

[10000 rows x 10 columns]
[[1 1 1 ... 0 1 1]
 [0 0 1 ... 1 1 1]
 [1 1 1 ... 1 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 1 ... 1 1 1]
 [0 1 0 ... 1 0 1]]


In [3]:
column_labels =  { # from https://docs.ultralytics.com/datasets/detect/coco/#dataset-yaml, It's the Yolo Dataset
  0: "person",
  1: "bicycle",
  2: "car",
  3: "motorcycle",
  4: "airplane",
  5: "bus",
  6: "train",
  7: "truck",
  8: "boat",
  9: "traffic light",
}

source_data_df.rename(columns=column_labels, inplace=True)
print(source_data_df)

      person  bicycle  car  motorcycle  airplane  bus  train  truck  boat  \
0          1        0    0           0         0    0      0      0     0   
1          0        1    1           0         1    1      0      1     1   
2          1        0    1           0         0    1      1      1     0   
3          0        1    1           0         1    1      1      1     0   
4          1        1    0           0         1    1      0      0     0   
...      ...      ...  ...         ...       ...  ...    ...    ...   ...   
9995       0        1    0           1         1    1      0      0     1   
9996       0        1    0           1         0    0      0      0     1   
9997       0        0    1           0         0    1      0      1     1   
9998       1        1    1           1         1    0      0      1     1   
9999       1        0    1           0         0    0      0      0     1   

      traffic light  
0                 0  
1                 1  
2        

In [4]:
# check if all numbers are correct
# TODO: What is the a pandas way?

amount = 0

for row in source_data_df:
    for item in source_data_df[row]:
        if item != 0:
            if item != 1:
                amount += 1

print(amount)

0


In [5]:
# Adding the answerous column, y. 
# signals: 1 = keep, 0 = delete

# create the answer_column. For n
# TODO: how to add headline at once?
answers_column = pd.DataFrame(index=np.arange(10000), columns=np.arange(1))
# print(len(answers_column))

answers_column.rename(columns={0:"Throw_or_Keep"}, inplace=True) # TODO: Why is not tuple and list working for columns?
# print(answers_column)

source_data_df = source_data_df.join(answers_column) # TODO: Not persistent. What is the pandas way?
print(source_data_df)



      person  bicycle  car  motorcycle  airplane  bus  train  truck  boat  \
0          1        0    0           0         0    0      0      0     0   
1          0        1    1           0         1    1      0      1     1   
2          1        0    1           0         0    1      1      1     0   
3          0        1    1           0         1    1      1      1     0   
4          1        1    0           0         1    1      0      0     0   
...      ...      ...  ...         ...       ...  ...    ...    ...   ...   
9995       0        1    0           1         1    1      0      0     1   
9996       0        1    0           1         0    0      0      0     1   
9997       0        0    1           0         0    1      0      1     1   
9998       1        1    1           1         1    0      0      1     1   
9999       1        0    1           0         0    0      0      0     1   

      traffic light Throw_or_Keep  
0                 0           NaN  
1  

In [6]:
# calculate if all elements are present, giving a 0 or 1
source_data_df.loc[(source_data_df['bicycle'] == 1) 
                  & (source_data_df['bicycle'] == 1) 
                  & (source_data_df['bicycle'] == 1),
                  "Throw_or_Keep"] = 1

source_data_df.loc[(source_data_df['bicycle'] != 1) 
                  & (source_data_df['bicycle'] != 1) 
                  & (source_data_df['bicycle'] != 1),
                  "Throw_or_Keep"] = 0

print(source_data_df)

      person  bicycle  car  motorcycle  airplane  bus  train  truck  boat  \
0          1        0    0           0         0    0      0      0     0   
1          0        1    1           0         1    1      0      1     1   
2          1        0    1           0         0    1      1      1     0   
3          0        1    1           0         1    1      1      1     0   
4          1        1    0           0         1    1      0      0     0   
...      ...      ...  ...         ...       ...  ...    ...    ...   ...   
9995       0        1    0           1         1    1      0      0     1   
9996       0        1    0           1         0    0      0      0     1   
9997       0        0    1           0         0    1      0      1     1   
9998       1        1    1           1         1    0      0      1     1   
9999       1        0    1           0         0    0      0      0     1   

      traffic light Throw_or_Keep  
0                 0             0  
1  

In [14]:
source_data_np_array = source_data_df.to_numpy()
#print(source_data_df)
print(source_data_np_array)

[[1 0 0 ... 0 0 0]
 [0 1 1 ... 1 1 1]
 [1 0 1 ... 0 1 0]
 ...
 [0 0 1 ... 1 0 0]
 [1 1 1 ... 1 0 1]
 [1 0 1 ... 1 1 0]]


In [66]:
from sklearn import svm


X = source_data_np_array[0:, 0:9]
y = np.transpose(source_data_np_array[0:, 10:])
print(X.shape)
print(X)
print(y.shape)
print(y)

b = 1
print((b == 1))

print(X)
print((X == '1') | (X == '0'))

clf = svm.SVC()
clf.fit(X, y.flatten())


(10000, 9)
[[1 0 0 ... 0 0 0]
 [0 1 1 ... 0 1 1]
 [1 0 1 ... 1 1 0]
 ...
 [0 0 1 ... 0 1 1]
 [1 1 1 ... 0 1 1]
 [1 0 1 ... 0 0 1]]
(1, 10000)
[[0 1 0 ... 0 1 0]]
True
[[1 0 0 ... 0 0 0]
 [0 1 1 ... 0 1 1]
 [1 0 1 ... 1 1 0]
 ...
 [0 0 1 ... 0 1 1]
 [1 1 1 ... 0 1 1]
 [1 0 1 ... 0 0 1]]
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]


ValueError: Unknown label type: unknown. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [5]:
testpyarr = np.arange(3,5, 4)
print(testpyarr)

[3]
